pointoffset interpolation

diff --git a/build b/build
--- a/build
+++ b/build
@@ -110,11 +110,9 @@ cmake \
   .
 echo "STATUS	: building and installing gdelta"
 make
+if [ $? -ne 0 ]; then echo "ERROR	: make failed"; exit -1; fi
 sudo -E make install
-if [ $? -ne 0 ]; then
-  echo "ERROR	: make failed"
-  exit -1
-fi
+if [ $? -ne 0 ]; then echo "ERROR	: make failed"; exit -1; fi
 
 echo "----------------------------------"
 echo "DATE	: `date`"
